import { makeStyles } from "@mui/styles";

const useStyles = makeStyles((theme) => ({
  "cart__wrapper-content--info": {
    padding: "16px",
    background: "white",
    borderRadius: "8px",
  },
  info__voucher: {
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    cursor: "pointer",
    paddingTop: "10px",
  },
  coupon__list: {
    // overflow: "hidden",
    // maxHeight: "292px",
    // display: "grid",
    gap: "12px",
    padding: " 8px 5px",
  },
  code: {
    borderRadius: "4px",
    boxShadow: "none",
    border: "1px solid rgb(196, 196, 207)",
    height: "36px",
    width: "100%",
    color: "rgb(36, 36, 36)",
    fontSize: "14px",
    lineHeight: "20px",
    padding: "8px 12px 8px 44px",
    outline: "0px",
  },
  coupon__content: {
    position: "absolute",
    top: "0px",

    left: "0px",
    width: "100%",
    height: "100%",
    display: "flex",
  },
  coupon__image: {
    minWidth: "132px",
    width: "132px",
    height: "132px",
    padding: "8px",
    display: "flex",
    flexDirection: "column",
    position: "absolute",
    alignItems: "center",
    alignSelf: "center",

    justifyContent: "center",
  },
  "coupon__content-right": {
    width: "70%",
    height: "100%",
    display: "flex",
    padding: "12px",
    justifyContent: "center",
    position: "absolute",
    right: 0,
    flexDirection: "column",
  },
  coupon__item: {
    position: "relative",
    opacity: 1,
    // width: "90%",
    // backgroundColor:"red",
    zIndex: 2,
    height: "132px",
    marginBottom: "10px",
    margin: "0 25px",
  },
  btn__apply: {
    fontWeight: 500,
    letterSpacing: "0px",
    cursor: "pointer",
    textAlign: "center",
    borderRadius: "4px",
    outline: "none",
    fontSize: "15px",
    lineHeight: "24px",
    padding: "2px 12px",
    color: "rgb(255, 255, 255)",
    backgroundColor: "rgb(1, 127, 255)",
    border: "none",
    whiteSpace: "nowrap",
    marginLeft: "auto",
  },
}));

export default useStyles;
